sonar.projectKey=nodejs
sonar.host.url=http://sonarqube.sonarqube.svc.cluster.local:9000
sonar.login=squ_7364a8f05cfb24a98184cdae3fde280566aa14b8

# Optional
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,dist/**,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
