---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: nodejs-api
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: nodejs-api
    template:
      ref: nodejs-api
