apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: git
  name: git-update-deployment
  labels:
    app.kubernetes.io/version: '0.2'
    operator.tekton.dev/provider-type: community
spec:
  description: >-
    This Task can be used to update image digest in a Git repo using kustomize.
  params:
    - name: GIT_REPOSITORY
      type: string
    - name: GIT_REF
      type: string
    - name: CURRENT_IMAGE
      type: string
    - name: NEW_IMAGE
      type: string
    - name: NEW_DIGEST
      type: string
    - name: KUSTOMIZATION_PATH
      type: string
  results:
    - description: The commit SHA
      name: commit
  steps:
    - image: docker.io/alpine/git:v2.26.2
      name: git-clone
      env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: token
      script: |
        rm -rf git-update-digest-workdir
        REPO_URL=$(echo "$(params.GIT_REPOSITORY)" | sed "s|https://|https://${GIT_TOKEN}@|")
        git clone "${REPO_URL}" -b "$(params.GIT_REF)" git-update-digest-workdir
      workingDir: $(workspaces.workspace.path)
    - image: quay.io/wpernath/kustomize-ubi:latest
      name: update-digest
      script: |
        cd git-update-digest-workdir/$(params.KUSTOMIZATION_PATH)
        kustomize edit set image $(params.CURRENT_IMAGE)=$(params.NEW_IMAGE)@$(params.NEW_DIGEST)
        echo "##########################"
        echo "### kustomization.yaml ###"
        echo "##########################"
        cat kustomization.yaml
      workingDir: $(workspaces.workspace.path)
    - image: docker.io/alpine/git:v2.26.2
      name: git-commit
      env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: token
      script: |
        cd git-update-digest-workdir
        git config user.email "tektonbot@redhat.com"
        git config user.name "Tekton Pipeline Bot"
        git status
        git add $(params.KUSTOMIZATION_PATH)/kustomization.yaml
        git commit -m "[ci] Image digest updated"
        git push
        RESULT_SHA="$(git rev-parse HEAD | tr -d '\n')"
        EXIT_CODE="$?"
        if [ "$EXIT_CODE" != 0 ]; then
          exit $EXIT_CODE
        fi
        echo -n "$RESULT_SHA" > $(results.commit.path)
      workingDir: $(workspaces.workspace.path)
  workspaces:
    - description: The workspace for git operations.
      name: workspace
