apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonarqube-scan
  labels:
    app.kubernetes.io/version: '0.1'
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "code-quality"
spec:
  description: |
    This Task runs a SonarQube scan using the .NET SonarScanner.
  workspaces:
    - name: source
      description: The workspace containing the source code to scan
  steps:
    - name: sonar-scan
      image: quay.io/rh-ee-srehman/dotnettool:v5
      env:
        - name: DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER
          value: "0"
        - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
          value: "true"
        - name: DOTNET_CLI_TELEMETRY_OPTOUT
          value: "1"
        - name: SONAR_TOKEN
          valueFrom:
            secretKeyRef:
              name: sonarqube-secret
              key: SONAR_TOKEN
      script: |
        cd $(workspaces.source.path)
        cd SampleApplication
        ls 
        export PATH="$PATH:/root/.dotnet/tools"
        ls /root/.dotnet/tools
        dotnet build --no-restore
        dotnet sonarscanner begin /k:"$(params.SONAR_PROJECT_KEY)" /d:sonar.host.url="$(params.SONAR_HOST_URL)" /d:sonar.login="$SONAR_TOKEN"
        echo "COMPLETED SONAR SCANNER"
        dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
        echo "COMPLETED LAST STEP"