apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonarqube-scan
  labels:
    app.kubernetes.io/version: '0.1'
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "code-quality"
spec:
  description: |
    This Task runs a SonarQube scan using the .NET SonarScanner.
  workspaces:
    - name: source
      description: The workspace containing the source code to scan
  steps:
    - name: sonar-scan
      image: quay.io/rh-ee-srehman/nodetool:v1
      script: |
        cd $(workspaces.source.path)
        npm i
        sonar-scanner